[bar]
order = [ "default" ]

    [bar.default]
    capsule = true
    end = [ "tray", "group:g1", "group:g2", "session" ]
    font_family = "JetBrainsMono Nerd Font"
    layer = "top"
    margin_edge = 0
    margin_ends = 0
    radius = 9
    radius_bottom_left = -10
    radius_bottom_right = -10
    radius_top_left = -80
    radius_top_right = -80

        [[bar.default.capsule_group]]
        fill = "surface_variant"
        id = "g1"
        members = [ "network", "bluetooth" ]
        opacity = 1.0
        padding = 10.0

        [[bar.default.capsule_group]]
        fill = "surface_variant"
        id = "g2"
        members = [ "brightness", "volume", "battery" ]
        opacity = 1.0
        padding = 10.0

        [[bar.default.capsule_group]]
        fill = "surface_variant"
        id = "g3"
        members = [ "launcher", "clock" ]
        opacity = 1.0
        padding = 6.0

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 1280.0
    cy = 1481.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_login_button = true

[shell]
font_family = "JetBrainsMono Nerd Font"
settings_show_advanced = true

    [[shell.session.actions]]
    action = "lock"
    command = "hyprlock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[theme]
builtin = "Catppuccin"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

    [theme.templates]
    builtin_ids = [ "foot", "gtk3", "gtk4", "hyprland", "kcolorscheme", "qt" ]
    community_ids = [ "discord" ]

[wallpaper]
directory = "/home/autumn/Pictures"

    [wallpaper.default]
    path = "/home/autumn/Pictures/wallhaven-2k33rx_2560x1600.png"

    [wallpaper.last]
    path = "/home/autumn/Pictures/wallhaven-2k33rx_2560x1600.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/autumn/Pictures/wallhaven-2k33rx_2560x1600.png"

[widget.brightness]
show_label = false

[widget.clock]
capsule = true
capsule_padding = 16.0
format = "{:%I:%M %p}"

[widget.network]
show_label = false

[widget.volume]
show_label = false
